# Generated by Django 2.2.17 on 2020-12-13 06:28

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='branch_name_gin_trgm_index', opclasses=['gin_trgm_ops']),
        ),
    ]
