# Generated by Django 2.2.17 on 2020-12-13 06:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['first_name'],
                name='employee_fname_gin_index',
                opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['last_name'],
                name='employee_lname_gin_index',
                opclasses=['gin_trgm_ops']),
        ),
    ]
